### ISSUE TITLE
Dėl prioritetų svorių

### ISSUE THREAD

**Issue by Skirtum** [vilnius/mokyklos#1]
Ar prioritetai CR_1, CR_2, ... CR_13 yra skirtingo svorio ar vienodo? 

Kalbu apie šį sąrašą: https://github.com/vilnius/mokyklos/blob/master/data/Mokyklu%20prasimai%20pagal%20istaigas_request_list.csv

Kaip elgiamasi tokiu atveju, kai tarkime 50 vaikų turi vienodą prioritetą, bet iš jų tik 30 telpa. Pagal ką parenkama, kurie telpa kurie ne? Pagal registracijos seniūnijoje datą? Ar galima deklaruotą registracijos datą susieti su "PRASYMO_ID"?

**Comment by Skirtum** [comment]
Jau pamačiau čia, kad svoriai vienodi: https://github.com/vilnius/mokyklos/blob/master/Galimi%20prioritetai.csv

Antras klausimas išlieka: kas nusprendžia kurie vaikai patenka, o kurie ne, jei prioritetų kiekis vienodas?

**Comment by Skirtum** [comment]
Dar vienas klausimas: ar teikiami prioritetai pavyzdžiui pirmai klasei prieš kitas klases? T.y. jei vaikų yra ir į 1, 2 ar 12 klasę norinčių mokytis toje mokykloje, tai prioritetas kaip nors dalinamas ar vienodas visiems?

**Comment by jonaspidkovas** [comment]
Svoriai nevienodi, sistemoje kol svoriu neskaičiuoja, eiles nerikiuojamos:
Svorius galite rasti čia: ©http://www.vilnius.lt/vaktai2011/default.aspx?Id=3&DocId=30288630&KlasId=42
Pridėjome lauką deklaruotas nuo, po pietų turėtų atsinaujinti
